namespace csvgenerator;

public class NameGenerator
{
    // List to store names generated by the generator
    private List<string> names = new List<string>();

    // Allows other methods to get the list of names
    public List<string> getNames()
    {
        return names;
    }

    // Method will generate names based on quantity specified by user
    public void generateNames(int quantity)
    {
        
    }
} // End of Class